# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojp', '0002_auto_20161116_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_num',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
